config/routes.rb
Rails.application.routes.draw do
  resources :courses, except: [:show, :edit]
  resources :course_categories do
  	resources :courses, only: [:show, :edit]
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
	require 'carrierwave/orm/activerecord'
  
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :course_category
  mount_uploader :course_banner_image, ImageUploader
  extend FriendlyId
  friendly_id :name, use: :slugged
 end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
   has_many :course

   extend FriendlyId
   friendly_id :name, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/course_categories_controller.rb
class CourseCategoriesController < ApplicationController
  before_action :set_course_category, only: [:show, :edit, :update, :destroy]

  # GET /course_categories
  # GET /course_categories.json
  def index
    @course_categories = CourseCategory.all
  end

  # GET /course_categories/1
  # GET /course_categories/1.json
  def show
  end

  # GET /course_categories/new
  def new
    @course_category = CourseCategory.new
  end

  # GET /course_categories/1/edit
  def edit
  end

  # POST /course_categories
  # POST /course_categories.json
  def create
    @course_category = CourseCategory.new(course_category_params)

    respond_to do |format|
      if @course_category.save
        format.html { redirect_to @course_category, notice: 'Course category was successfully created.' }
        format.json { render :show, status: :created, location: @course_category }
      else
        format.html { render :new }
        format.json { render json: @course_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_categories/1
  # PATCH/PUT /course_categories/1.json
  def update
    respond_to do |format|
      if @course_category.update(course_category_params)
        format.html { redirect_to @course_category, notice: 'Course category was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_category }
      else
        format.html { render :edit }
        format.json { render json: @course_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_categories/1
  # DELETE /course_categories/1.json
  def destroy
    @course_category.destroy
    respond_to do |format|
      format.html { redirect_to course_categories_url, notice: 'Course category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_category
      @course_category = CourseCategory.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_category_params
      params.require(:course_category).permit(:name, :description, :slug)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end


  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_category_course_path(@course.course_category, @course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_category_course_path(@course.course_category, @course), notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :course_category_id, :slug ,:course_banner_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_categories_helper.rb
module CourseCategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/course_categories/_form.html.erb
<%= form_for(course_category) do |f| %>
  <% if course_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_category.errors.count, "error") %> prohibited this course_category from being saved:</h2>

      <ul>
      <% course_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description , class: "ckeditor" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
$(document).ready(function() {
 $(".ckeditor").ckeditor({
  })
  });
</script>

app/views/course_categories/edit.html.erb
<h1>Editing Course Category</h1>

<%= render 'form', course_category: @course_category %>

<%= link_to 'Show', @course_category %> |
<%= link_to 'Back', course_categories_path %>

app/views/course_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_categories.each do |course_category| %>
      <tr>
        <td><%= course_category.name %></td>
        <td><%= course_category.description %></td>
        <td><%= link_to 'Show', course_category %></td>
        <td><%= link_to 'Edit', edit_course_category_path(course_category) %></td>
        <td><%= link_to 'Destroy', course_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Category', new_course_category_path %>

app/views/course_categories/new.html.erb
<h1>New Course Category</h1>

<%= render 'form', course_category: @course_category %>

<%= link_to 'Back', course_categories_path %>

app/views/course_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course_category.description.html_safe %>
</p>

<%= link_to 'Edit', edit_course_category_path(@course_category) %> |
<%= link_to 'Back', course_categories_path %>

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "ckeditor" %>
  </div>

  <div class="field">
    <%= f.label :course_category_id %>
    <%= f.text_field :course_category_id %>
  </div>

  <div class="field">
    <%= f.label :Upload_Banner_Image %>
    <%= f.file_field :course_banner_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
 $(".ckeditor").ckeditor({
  })
  });
</script>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', course_category_course_path(@course.course_category, @course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Course category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.course_category.try(:name) %></td>
        <td><%= link_to 'Show', course_category_course_path(course.course_category, course) %></td>
        <td><%= link_to 'Edit', edit_course_category_course_path(course.course_category, course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
	<div class="row">
		<div class="col-md-9 col-sm-9">
			<div class="">
				<h1><strong><%= link_to @course.course_category.name, course_category_path(@course.course_category) %> / <%= @course.name %></strong></h1>
			</div>
			<div class="banner-img course-page">
				<%= image_tag @course.course_banner_image_url, class: "img-responsive" %>
			</div>

			<div class="course-page">
				<h3><strong>Course Details</strong></h3>
				<p><%= @course.description.html_safe %></p>
			</div>
			<%= link_to 'Edit', edit_course_category_course_path(@course.course_category, @course) %> |
			<%= link_to 'Back', courses_path %>
		</div>
		<div class="col-md-3">
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NSDigitalSolution</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>